### PR TITLE
gofumpt -w -l .

### PR DESCRIPTION
**Pull request by faddat**
excellent code formatting for golang

go install mvdan.cc/gofumpt@latest
gofumpt -w -l .

### CODE REVIEW

**Comment by ankurdotb** [comment]
@askolesov Seems like a good chore, can you take a look please and see if you agree?

**Comment by askolesov** [comment]
Yeah, looks good. I suggest then adding a linter rule to check formatting. @ankurdotb Would you agree?

**Comment by ankurdotb** [comment]
> Yeah, looks good. I suggest then adding a linter rule to check formatting. @ankurdotb Would you agree?

Yep sounds good to me! Maybe as a step in the Go lint job?

**Comment by askolesov** [comment]
@faddat Thanks! Wasn't able to commit to your branch, so created another PR: https://github.com/cheqd/cheqd-node/pull/324. Your commits are preserved. In future, please allow pushes - there should be a checkbox when you create a PR.

**Pull request closed without merging**
