### PR TITLE
feat: add msg mint

### PR DESCRIPTION
**Pull request by atheeshp**

### CODE REVIEW

**Comment by Eengineer1** [comment]
@atheeshp I've rebased the PR to target the latest ante, post handler PR branch so that synchronisation remains intact.

Could you please resolve the conflicts?

**Comment by Eengineer1** [comment]
@atheeshp Could you please resolve conflicts + merge in latest develop?

**Comment by Eengineer1** [comment]
@atheeshp Could you please resolve conflicts + merge in latest develop?

> @atheeshp Could you please resolve conflicts + merge in latest develop?

Or @vishal-kanna, depending on availability.

**Comment by vishal-kanna** [comment]
Okay

**Comment by Eengineer1** [comment]
@vishal-kanna What's the latest update here?

We'd ideally want to restore both the integration + upgrade test suites relatively soon.

**Pull request merged**
