### PR TITLE
test: Add interactive installer to workflow and get rid of deb

### PR DESCRIPTION
**Pull request by anikitinDSR**

### CODE REVIEW

**Comment by ankurdotb** [comment]
Task linked: [DEV-1523 Build Cosmovisor install + upgrade using interactive installer into workflow](https://app.clickup.com/t/6600954/DEV-1523)

**Review by rosspower11 — APPROVED** [review]
approved

**Review by Toktar — APPROVED** [review]

**Comment by Toktar** [comment]
@askolesov Could you double-check?

**Review by askolesov — APPROVED** [review]
Looks good. What can be improved, in my opinion - we use of `sudo` too much

**Pull request merged**
